### PR TITLE
Arch migrate

### PR DESCRIPTION
**Pull request by martin-g**
Based on top of https://github.com/conda-forge/perl-dbi-feedstock/pull/4

* Build PPC64LE on Azure CI (cross compilation)
* Add stdlib('c')

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
The PPC64LE build fails due to: `nothing provides perl-storable needed by perl-test-simple-1.302191-pl5321hd8ed1ab_0`. I will remove it!

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please ping team
Please review!

**Comment by martin-g** [comment]
@conda-forge/core Could you please help with the review and merge of this PR ? Thank you!

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
